# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9033d799d06909767add5fc4d1c29b29735b0d9f47d24e7b078f8410b952996dac46acb009fd382a9cfdc5f67c863815aa89a8e825ec8c0c76fcc0377ba222c1

test:
  secret_key_base: 4f2df142c99b302fd4ced431c86dc1e70df258206ab60c81d80e8971d56a831410c87f9834d855c097fafed3ae2e6ae557c4b40490725a90ca91209b7320bebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
